### ISSUE TITLE
Cannot get property 'packageName' on null object

### ISSUE THREAD

**Issue by alzalabany** [JBuijgers/nx-react-native#1]
followed exact guide on fresh nx work space ended up with 

**Cannot get property 'packageName' on null object**

**Comment by JBuijgers** [comment]
Can you give tell me which version of react-native CLI you have running globally? This happens to me if I have 2.9.x running globally, even though this package is using the beta version of react-native-cli.

This is quirky thing that is currently in react-native-cli package, it happens when https://github.com/react-native-community/cli/blob/master/packages/platform-android/native_modules.gradle#L155 is executed, the npx ... command will try to use the globally installed rn-cli. The output from this command is mostly empty, because the 2.9.x version looks in the wrong directory to generate the config (not sure which directory it was). The beta version works a bit different, instead of dumping a mostly empty config, it will go up a few directories to find the needed files to generate a complete config.

This will be fixed in the future, either by the rn-cli package itself, using something like https://github.com/flisboac/react-native-monorepo-helper or generating the config when generating the app (nx g app). The last one will create an extra file called react-native.config.js, which will contain all the config values and is used by v2 and v3 (if I'm not mistaken) of react-native-cli.

**Comment by asherccohen** [comment]
This might be an issue with react-native-cli. Remove the cli from your global npm and retry.
